openapi: 3.0.0
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/GRIFFINHENRY07_1/campyuk/1.0.0
info:
  version: "1.0.0"
  title: Campyuk App Project
  description: The API for the EatBacon IOT project
tags:
  - name: auth
  - name: users
  - name: camps
  - name: items
  - name: bookings
paths:
  